### ISSUE TITLE
[REQUEST] Update Freyja to 1.5.1

### ISSUE THREAD

**Issue by arianna-smith** [CDPHE-bioinformatics/CDPHE-SARS-CoV-2#21]
## Request
In `SC2_waste_water_variant_calling.wdl`, update Freyja docker container to 1.5.1.

### Upstream effects
None

### Downstream effects
None

### 1.4.8
Bug fixes, plus beta version of adaptive regularization method.

### 1.4.9
Includes a series of updates:
- Improved error message reporting to prevent hard to understand fail cases
- Dash and plot changes to prevent labels/legend from being cut off
- spike (or arbitrary genome region) coverage estimates
- options to retain intermediate outputs via dash/plot
- lineage hierarchy input for demix, plot, dash, relgrowthrate

### 1.5.0
- adds `--depthcutoff` features to account for available genome coverage, de-aliasing, and assignment of MRCAs
- enables both true and relaxed MRCA assignment
- incorporates collapsed MRCAs into summarization and plotting
- some small speed improvements
- option to set `variants` threshold above 0 for space constraints

### 1.5.1
- **changes default solver to clarabel, with options to use ecos and osqp**
- improvements to the covariants function
- small bug fixes, plotting improvements
- switches barcodes to feather format, for faster loading and smaller file size.

## Affected code
Script: `SC2_waste_water_variant_calling.wdl`
Tasks: 
- `freyja_demix` 
  - commands 
    - `freyja update`
    - `freyja demix --eps 0.01 --covcut 10` 
  - output files: `${sample_name}_demixed.tsv`
- `freyja_aggregate` 
  - commands
    - `freyja aggregate`
  - output files: `demix_aggregated.tsv

## Differences
`freyja demix` new parameters:
`--adapt FLOAT` - adaptive lasso penalty parameter  [default: 0.0]
`--a_eps FLOAT` - adaptive lasso parameter, hard threshold [default: 1e-08]
`--region_of_interest TEXT` - JSON file containing region(s) of interest for which to compute additional coverage estimates
`--relaxedmrca` - for use with depth cutoff,clusters are assigned robust mrca to handle outliers
`--relaxedthresh FLOAT` - associated threshold for robust mrca function [default: 0.9]
`--solver TEXT` - solver used for estimating lineage prevalence [default: CLARABEL]

For demixing, solver used in 1.4.7 was `ecos`. The default has updated to `clarabel` (solver used by `cvxpy`, which is a Python-embedded modeling language for convex optimization problems). Do we want to update to this solver? Perform comparison?

**Comment by molly-hetheringtonrauth** [comment]
The new version release, fixes bugs. We don't think it affect any existing functionality. 

would require that we test the new version and check to see if any output changes. If output changes then would need to refactor code, otherwise just update docker.

**Comment by danpolanco** [comment]
There are some bug fixes but this requires more testing. There is more functionality in most recent releases we are interested in.

**Comment by arianna-smith** [comment]
Update to 1.5.1. From release notes:

- changes default solver to clarabel, with options to use ecos and osqp
- improvements to the covariants function
- small bug fixes, plotting improvements
- switches barcodes to feather format, for faster loading and smaller file size.

**Comment by arianna-smith** [comment]
Changing to immediate priority and hotfix because the barcodes stopped being updated in the csv on June 15, and only the newest version of Freyja pulls the correct barcodes feather file
