### ISSUE TITLE
[FEATURE] Create consistency between clinical and wwt mutation tracking

### ISSUE THREAD

**Issue by molly-hetheringtonrauth** [CDPHE-bioinformatics/CDPHE-SARS-CoV-2#24]
### Feature Request
Based on issue #23 (deprecate "nextclade_json_parser.py and use VCF file for mutations tracking), we should be able to more easily create consistency between how we track mutations found in clinical and wwt sample types. 

### Solution
- ivar does not handle MVNs, so we may want to explore using BCF tools.
TBD

### Upstream effects
TBD

### Downstream effects
TBD

**Comment by danpolanco** [comment]
We don't think we are going to need this as per discussion during data organization meeting.
