### ISSUE TITLE
[REQUEST] Version Capture Files for Sample Level Workflows

### ISSUE THREAD

**Issue by molly-hetheringtonrauth** [CDPHE-bioinformatics/CDPHE-SARS-CoV-2#36]
### Feature Request
The version capture output file lists the versions and docker containers for each program used in the workflow. The way we are handling version capture files for the sample level workflow causes an issue.  Currently, a version capture file for each sample is created and transferred to the bucket; however because each file is named the same, each sample's file overwrites the previous sample's file that was transferred to the bucket. This causes an issue, if the last file that is transferred is incomplete (ie. the sample failed). 

### Solution

- Add the sample name to the each file name, so that the files are not overwritten. And each sample's file will no longer be overwritten. 
- Currently the version capture files are output to the summary results directory. Because there will be a version capture file for each sample, we would like to create a separate version capture directory to store all the files. We will also want to push the set level version capture files here as well. 

### Upstream effects
None

### Downstream effects

- For sample level workflows there will be a version capture output file made for each sample. 
- All version capture output files will be stored in a new output directory called "version_capture".
- BigQuery @danpolanco ?

**Comment by danpolanco** [comment]
We currently do not import the version capture files into BigQuery so we have some flexibility here. We might want to try a few files to start, but I wouldn't make that a hard requirement since they `csv`. Instead, since we might not ever need the version capture files in BigQuery, I'd say we cross that bridge when we get there. Open to other opinions though!

**Comment by danpolanco** [comment]
This may be obsolete if we change to set level workflows. See #38.
