### ISSUE TITLE
[BUG/REQUEST] Update Artic to 1.5.2 for variant calling improvement and minor bug fix

### ISSUE THREAD

**Issue by arianna-smith** [CDPHE-bioinformatics/CDPHE-SARS-CoV-2#71]
# Description
Note- This issue describes a bug in a software called in the ONT assembly workflow, not in this codebase. 

When running `artic minion --medaka`, there is occasionally an issue where there are overlapping pass variants from the different read groups that cause bcftools consensus to fail and generate an empty consensus file. See https://github.com/artic-network/fieldbioinformatics/issues/132 for more details.

There was a previous band-aid fix, #12, to check if generated consensus files were empty and if so, fail the sample.

# Solution
Artic has https://github.com/artic-network/fieldbioinformatics/pull/137 waiting to be merged into main which has a fix for this bug, among other feature additions. We can update to this version after it's released and there is a new docker container for it. We are currently using `staphb/artic:1.2.4-1.11.1`. Note- They have been using the dev branch for updating but haven't been pushing to main, so we didn't miss a bunch of updates and are using the most recent available version.

From the PR:
### Major Changes:

- Fieldbioinformatics now supports rapid barcoded (fragmented) primer trimming and normalisation
- Nanopolish has been removed completely due to several compatibility issues
- Medaka is now the recommended variant caller and will run by default
- Clair3 has been added as an experimental variant caller (can be used by providing the `--clair3` argument to `artic minion`. By default only r9.4.1 models are available but r10.4.1 models are available from the [ONT Rerio](https://github.com/nanoporetech/rerio) repository.
- Primer scheme fetcher has been updated to pull from the [quick-lab primal hub schemes repository](https://github.com/quick-lab/primerschemes). For schemes not available in this repository you may provide them directly with the arguments `--bed` and `--ref`.
- Automated docker builds pushing to [quay.io](https://quay.io/repository/artic/fieldbioinformatics) for use in nextflow pipelines etc.
- Remove some old functionality which is no longer relevant (basecalling, gather, etc)
- Re-implement CI as a gh action.
- Fix the https://github.com/artic-network/fieldbioinformatics/issues/125 by normalising variants against the pre-consensus using bcftools norm.
- Fix the annoying longshot https://github.com/artic-network/fieldbioinformatics/issues/91 by setting max cov to an arbitrarily high number (200000) if anyone has 200001 depth BAMs and this break things I apologise profusely and would love to know what you're trying to accomplish with this data.

**Comment by sam-baird** [comment]
Clair3 seems to be reducing the number of frameshifts in our consensus sequences compared to Medaka based on local testing.
