### ISSUE TITLE
[REQUEST] Use BED file as input to Medaka for primer trimming

### ISSUE THREAD

**Issue by sam-baird** [CDPHE-bioinformatics/CDPHE-SARS-CoV-2#75]
### Feature Request
The BED file input was removed from the `Medaka` task in [December 2023](https://github.com/CDPHE-bioinformatics/CDPHE-SARS-CoV-2/commit/b52b5e3d9ea570688cb46217cc0a470a030adca8). Currently, the `primer_bed` file input is not used in this step for primer trimming, and the task is automatically pulling Artic BED v5.3.2 by default since it's the latest primer version, regardless of the primers actually used. 

### Solution
The task should take the BED file and/or the the specific Artic version as input.

### Upstream effects
None.

### Downstream effects
None.

**Comment by sam-baird** [comment]
We also probably want to pass in `covid_genome` as a custom input

**Comment by molly-hetheringtonrauth** [comment]
closed with PR #78
